@set adsk_clm_wpad_proxy_check=false
@set allusersprofile=c:\programdata
@set appdata=c:\users\nikel_000\appdata\roaming
@set asl.log=destination=file
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set computername=boss
@set comspec=c:\windows\system32\cmd.exe
@set devenvdir=d:\?????\common7\ide\
@set extensionsdkdir=c:\program files (x86)\microsoft sdks\windows kits\10\extensionsdks
@set fps_browser_app_profile_string=internet explorer
@set fps_browser_user_profile_string=default
@set fp_no_host_check=no
@set framework40version=v4.0
@set frameworkdir=c:\windows\microsoft.net\framework\
@set frameworkdir32=c:\windows\microsoft.net\framework\
@set frameworkversion=v4.0.30319
@set frameworkversion32=v4.0.30319
@set fsharpinstalldir=c:\program files (x86)\microsoft sdks\f#\4.0\framework\v4.0\
@set homedrive=c:
@set homepath=\users\nikel_000
@set include=d:\?????\vc\include;d:\?????\vc\atlmfc\include;c:\program files (x86)\windows kits\10\include\10.0.16299.0\ucrt;c:\program files (x86)\windows kits\netfxsdk\4.6.1\include\um;c:\program files (x86)\windows kits\10\include\10.0.16299.0\shared;c:\program files (x86)\windows kits\10\include\10.0.16299.0\um;c:\program files (x86)\windows kits\10\include\10.0.16299.0\winrt
@set lib=d:\?????\vc\lib;d:\?????\vc\atlmfc\lib;c:\program files (x86)\windows kits\10\lib\10.0.16299.0\ucrt\x86;c:\program files (x86)\windows kits\netfxsdk\4.6.1\lib\um\x86;c:\program files (x86)\windows kits\10\lib\10.0.16299.0\um\x86
@set libpath=c:\windows\microsoft.net\framework\v4.0.30319;d:\?????\vc\lib;d:\?????\vc\atlmfc\lib;c:\program files (x86)\windows kits\10\unionmetadata;c:\program files (x86)\windows kits\10\references;c:\program files (x86)\microsoft sdks\windows kits\10\extensionsdks\microsoft.vclibs\14.0\references\commonconfiguration\neutral
@set localappdata=c:\users\nikel_000\appdata\local
@set logonserver=\\boss
@set msbuildloadmicrosofttargetsreadonly=true
@set msbuildsdkspath=c:\program files (x86)\msbuild\sdks
@set msbuild_exe_path=d:\?????? ?????\pvs-studio\buildtools15\msbuild.exe;D:\Временные программы\PVS-Studio\BuildTools15\MSBuild.exe
@set netfxsdkdir=c:\program files (x86)\windows kits\netfxsdk\4.6.1\
@set number_of_processors=8
@set onedrive=c:\users\nikel_000\onedrive
@set openrda_ini=d:\?????? ?????\er\openaccess\bin\iwinnt\openrda.ini;D:\Временные программы\ER\OpenAccess\bin\iwinnt\openrda.ini
@set os=windows_nt
@set path=d:\?????\common7\ide\commonextensions\microsoft\testwindow;c:\program files (x86)\microsoft sdks\f#\4.0\framework\v4.0\;c:\program files (x86)\msbuild\14.0\bin;d:\?????\common7\ide\;d:\?????\vc\bin;d:\?????\common7\tools;c:\windows\microsoft.net\framework\v4.0.30319;d:\?????\vc\vcpackages;c:\program files (x86)\html help workshop;d:\?????\team tools\performance tools;c:\program files (x86)\windows kits\10\bin\x86;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\;d:\?????\common7\ide\commonextensions\microsoft\teamfoundation\team explorer\nativebinaries\x86;c:\programdata\oracle\java\javapath;c:\program files (x86)\intel\icls client\;c:\program files\intel\icls client\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files\intel\intel(r) management engine components\dal;c:\program files\intel\intel(r) management engine components\ipt;c:\program files (x86)\intel\intel(r) management engine components\dal;c:\program files (x86)\intel\intel(r) management engine components\ipt;c:\users\nikel_000\.dnx\bin;c:\program files\microsoft dnx\dnvm\;c:\program files\microsoft\web platform installer\;c:\program files (x86)\nvidia corporation\physx\common;c:\windows\system32\config\systemprofile\.dnx\bin;c:\program files (x86)\nodejs\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files\mysql\mysql utilities 1.6\;c:\program files\microsoft sql server\130\tools\binn\;c:\program files\qt\5.8\msvc2015\bin;c:\program files\dotnet\;c:\program files\matlab\r2016a\runtime\win64;c:\program files\matlab\r2016a\bin;c:\program files\matlab\r2016a\polyspace\bin;c:\users\nikel_000\appdata\local\programs\python\python36;c:\users\nikel_000\appdata\local\programs\python\python36\scripts;c:\users\nikel_000\appdata\local\android\sdk\platform-tools;c:\program files (x86)\windows kits\10\windows performance toolkit\;c:\users\nikel_000\appdata\roaming\npm;c:\users\nikel_000\appdata\local\microsoft\windowsapps;c:\users\nikel_000\appdata\local\programs\python\python36;c:\users\nikel_000\appdata\local\programs\python\python36\scripts;D:\Программы\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\NativeBinaries\x86
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
@set pkgdefapplicationconfigfile=c:\users\nikel_000\appdata\local\microsoft\visualstudio\14.0\devenv.exe.config
@set processor_architecture=amd64
@set processor_identifier=intel64 family 6 model 60 stepping 3, genuineintel
@set processor_level=6
@set processor_revision=3c03
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\windows\system32\windowspowershell\v1.0\modules\
@set public=c:\users\public
@set pvsbuildtoolsextensionspath=c:\program files (x86)\msbuild\
@set pvs_vsinstalldir=c:\program files (x86)\microsoft visual studio\2017\community
@set sessionname=console
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\nikel_~1\appdata\local\temp
@set tmp=c:\users\nikel_~1\appdata\local\temp
@set ucrtversion=10.0.16299.0
@set universalcrtsdkdir=c:\program files (x86)\windows kits\10\
@set userdomain=boss
@set userdomain_roamingprofile=boss
@set username=nikel_000
@set userprofile=c:\users\nikel_000
@set vbox_msi_install_path=c:\program files\oracle\virtualbox\
@set vcinstalldir=d:\?????\vc\
@set visualstudiodir=c:\users\nikel_000\documents\visual studio 2015
@set visualstudioedition=microsoft visual studio community 2015
@set visualstudioversion=14.0
@set vs110comntools=c:\program files (x86)\microsoft visual studio 11.0\common7\tools\
@set vs120comntools=c:\program files (x86)\microsoft visual studio 12.0\common7\tools\
@set vs140comntools=d:\?????\common7\tools\;D:\Программы\Common7\Tools\
@set vsinstalldir=d:\?????\
@set vslang=1049
@set vssdk140install=d:\?????\vssdk\;D:\Программы\VSSDK\
@set windir=c:\windows
@set windowslibpath=c:\program files (x86)\windows kits\10\unionmetadata;c:\program files (x86)\windows kits\10\references
@set windowssdkdir=c:\program files (x86)\windows kits\10\
@set windowssdklibversion=10.0.16299.0\
@set windowssdkversion=10.0.16299.0\
@set windowssdk_executablepath_x64=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\x64\
@set windowssdk_executablepath_x86=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\
@set _ptvs_pid=11360

@call cl.exe